name: Build Docker Images

on:
  push:
      branches:
        - main  

jobs:
 
  trigger-build:
    uses: multi-repo/workflows/.github/workflows/kaniko-build.yaml@main
    with:
      image-name: ${{ github.repository }}/redis
    secrets:
      personal_access_token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          
  trigger-cleanup:
      uses: multi-repo/workflows/.github/workflows/clean-registry.yaml@main
      with:
        owner: multi-repo
        repository: redis 
        package: redis/redis
        keep_n_tagged: 2
        dry_run: true  
      secrets:
        personal_access_token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}

  deploy:
    needs: [trigger-cleanup, trigger-build]
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to environment
        run: |
          echo "Deploying application"


          
